### ISSUE TITLE
Set content type as option

### ISSUE THREAD

**Issue by fdelbos** [viant/afs#11]
Hi!

I want to set the content type of the file when i save it to cloud storage (ex: `image/jpeg`), but cant find the correct option for my call:
```go
wc, err := afs.New().NewWriter(ctx, dest, 0644)
```

(by the way thanks for this package, its awesome!)

**Comment by adranwit** [comment]
You can use content.Meta option,

	fs := New()
	wc, err := fs.NewWriter(ctx, dest, 0644, content.NewMeta(content.Type, "image/jpeg"))
