### ISSUE TITLE
unzip dir.zip

### ISSUE THREAD

**Issue by Alex-query** [viant/afs#20]
i use this code to zip and unzip folder

> service := afs.New()
> ctx := context.Background()
> uploader := zip.NewBatchUploader(file.New())
> err := service.Copy(ctx, "deployments", "zipped.zip", uploader)
> if err != nil {
> log.Fatal(err)
> }

> walker := zip.NewWalker(file.New())
> err = service.Copy(ctx, "zipped.zip", "zipped", walker)
> if err != nil {
> log.Fatal(err)
> }

zip - works properly , but uzip doesn`t

i zipped folder with one file "deployments\docker-compose\docker-compose.yml"
As result after unzip , i get "zipped\docker-compose\zipped.zip" . An intresting thing is that "zipped\docker-compose\zipped.zip" is a txt file with rigth conent . But name of folder is wrong

**Comment by adranwit** [comment]
Could you please provide an archive that unzip does not work propertly, thanks in advance

**Comment by Alex-query** [comment]
[zipped.zip](https://github.com/viant/afs/files/11311726/zipped.zip)

**Comment by adranwit** [comment]
The issue has been addressed in https://github.com/viant/afs/releases/tag/v1.23.1

**Comment by adranwit** [comment]
Thank for contributing

**Comment by Alex-query** [comment]
@adranwit i decided to try again, but i have a problem with this zip file " mkdir ........zipped/: Cannot create a file when that file already exists" i use v1.24.2
