### ISSUE TITLE
Difference from affero

### ISSUE THREAD

**Issue by damooo** [viant/afs#7]
Hello, thanks for great lib.

If possible, can you briefly specify, what is `afs` different from [https://github.com/spf13/afero](https://github.com/spf13/afero) in it's motivation and implementation.

And can we pass opened file to other tools which expects native file interface?

Thanks.

**Comment by adranwit** [comment]
https://github.com/spf13/afero looks likes a nice library.


The very orgin of abstract file store comes e2e testability [endly](https://github.com/viant/endly) project introduced Sep 2017.
Many endly dependencies including abstract file systems were defined in toolbox project, storage [storage](https://github.com/viant/toolbox/tree/master/storage) package.  Overtime toolbox project become cluttered (failing many good code quality code marks),  so I've decided to move various abstraction as separate projects including storage, there was I few things I've to learn about limitation of original toolbox storage design like streaming large datafile on the cloud, improving SCP support (especially performance), walking and embedding archives in another storage system (super important when needs to deploy a single property file in a war file),  testability (simulating data operation errors also in e2e testing) , so I've addressed them while moving original storage implementation to viant/afs. 

We use endly and thus an abstract storage system (initally tooobx now afs) to automate development, deployment (AWS lambda, GCP Cloud Functions)  and testing workflow all over the places, and being storage agnostic (mostly cloud).

I do not recall back in 2017 seeing  https://github.com/spf13/afero,  but I guess both viant/toolbox storage and its successor viant/afs comes initially from pure e2e testing use cases needs to be SCP/cloud agnostic.

**Comment by adranwit** [comment]
When working with afs,  specifically with os native file system, the implementation uses directly *os.File type, for  Open or OpenURL or NewWriter methods, so you can cast it as *os.File if needed to work with other libraries.

For example, [hyper performant transaction logger ](https://github.com/viant/tapper) leverage benefit or native OS file implementation while it also supports all other file systems.

**Comment by damooo** [comment]
Thanks a lot for detailed descr @adranwit .

I should also check endly, as it seems addressing our case of testing against data stores in coherent way.

Thanks for your work.

**Comment by adranwit** [comment]
feel free to  join endly channel on gophers.slack.com
